
# SEO settings
title: "Linux study"
title2: " of Hongseokzip" # default: ""
description: "Linux study of Hongseokzip members"
keywords: "linux, hongseokzip"
url: https://hongseokzip.github.io/Linux_Study # site url
baseurl: null # apply repo name if use it under gh-pages branch

# google_analytics: UA-XXXXX-XX
repo: https://github.com/Hongseokzip/Linux_Study
disqus_shortname: "hongseokzip"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Hongseokzip"
  job      : "community"
  bio      : "Welcome to Hongseokzip"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
